replicaCount: 1

image:
  repository: myrepo/auth-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: auth.example.com
  path: /
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

